<?php
/**
 * Created by PhpStorm.
 * User: carlosherrera
 * Date: 17/11/17
 * Time: 12:04 PM
 */

class WP_Widget_Chilean_Weather_Indicators extends WP_Widget_Chilean_Indicators {
	public $apiUrl = 'http://api.openweathermap.org/data/2.5/weather?appid=%s&units=metric&lang=%s&%s';
	public $city;
	public $expire = 0;

	public function __construct() {

		$this->city = function_exists( 'bp_get_profile_field_data' ) && bp_get_profile_field_data( array(
			'field'   => 'Location',
			'user_id' => get_current_user_id()
		) ) ?: null;
		parent::__construct(
			'chilean-weather-indicators', //ID
			'Chilean Weather Indicators', //Nombre
			array(
				'classname'   => 'widget_chilean_weather_indicators',
				'description' => ''
			)
		);
	}


	public function widget( $args, $instance ) {
		$this->instance = $instance;
		if ( ! isset( $instance['apikey'] ) || ! $instance['apikey'] ) {
			new WP_Error( 'apikey missing' );

			return;
		} else {

			if ( isset( $instance['lang'] ) && $instance['lang'] ) {
				$lang = $instance['lang'];
			} else {
				$lang = 'es';
			}
			if ( $this->city ) {
				$q = 'q=' . $this->city;
			} elseif ( isset( $instance['city'] ) && $instance['city'] ) {
				$q = 'q=' . $instance['city'];
			} else {
				if ( isset( $instance['lat'] ) && $instance['lat'] &&
				     isset( $instance['lon'] ) && $instance['lon'] ) {
					$q = 'lat=' . $instance['lat'] . '&lon=' . $instance['lon'];
				} else {
					$q = 'q=Santiago, Chile';
				}
			}

			$this->apiUrl = sprintf( $this->apiUrl,
				$instance['apikey'],
				$lang,
				$q );
			echo '<div class="WP_Widget_Chilean_Indicators WP_Widget_Chilean_Weather_Indicators">';
			echo '<ul>';
			echo $this->printWeather();
			echo '</ul>';
			echo '</div>';
		}


	}

	public function printWeather() {
		$key   = 'weather';
		$label = $this->instance['title'];
		$value = ',' . $this->data()->main->temp . '°C ' . $this->data()->weather[0]->description;

		return $this->printValue( $key, $value, $label );
	}

	public function form( $instance ) {
		parent::form( $instance );
		echo $this->formInput( $instance
			, 'apikey'
			, 'Apikey de openweathermap.org:'
			,
			'Para usar este Widget necesitas una apikey de openweathermap.org<br><a href="http://openweathermap.org" target="_blank">openweathermap.org</a>'

		);
		echo '<hr>';
		if ( $this->city ) {
			echo '<p><strong>Usando Perfil extendido de BuddyPress. Crea un campo location para usar este widget</strong></p>';
		} else {
			echo $this->formInput( $instance
				, 'city'
				, 'Ciudad'
				, 'Si elijes escribir una latitud y longitud se usará por sobre la ciudad'
			);
			echo $this->formInput( $instance
				, 'lat'
				, 'Latitud'
			);
			echo $this->formInput( $instance
				, 'lon'
				, 'Longitud'
			);
			echo $this->formInput( $instance
				, 'lang'
				, 'Lenguaje'
				, ''
				, 'es'
			);


		}

	}

	public function update( $new_instance, $old_instance ) {
		return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
	}


}